"""Recommendation decision journal (BTC-200).

The advisory path stops at a rendered recommendation. What the operator then
did with it is the one fact no model-side record can hold, and without it the
paper record and the human record cannot be compared at all.

A decision here is a statement about an *advisory*, not about a trade. Two of
the four decisions -- ``REJECTED`` and ``MISSED`` -- never produce a fill, so
they cannot be written into the BTC-017 manual execution journal, whose every
column below the decision describes one. That journal keeps its own vocabulary
and remains the place where an actual execution is recorded.

Three properties make an entry worth trusting later:

* It carries the BTC-166 provenance triple, taken from the same owner the paper
  lifecycle uses, so a decision is attributable to the exact strategy version
  and parameter set that produced the advisory rather than to whatever is
  configured when the record is read.
* It stores the canonical BTC-172 advisory document verbatim, with a digest
  over those exact bytes. A decision is only auditable against what the
  operator was actually shown; a later re-render of "the same" recommendation
  is not evidence of that.
* It refuses decisions that the advisory cannot support. ``MODIFIED`` names
  which advised values were departed from and requires that the advisory
  actually stated them, and neither ``MODIFIED`` nor ``MISSED`` is accepted
  against an advisory that asked for no order, because there is nothing there
  to modify or to miss.

The actual entry, size, stop and exit of any resulting trade stay with BTC-202;
this module deliberately records which advised values were departed from, never
the values chosen instead. BTC-201 adds a separate, closed vocabulary for the
operator's discretionary reasons. These are not model-side explanation codes,
and ``note`` remains free single-line text rather than being interpreted as one.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import Any

from btc_predictor.config.strategy import StrategyConfig
from btc_predictor.data import require_utc_datetime
from btc_predictor.db.portfolio import (
    RECOMMENDATION_DECISIONS,
    recommendation_decisions,
)
from btc_predictor.portfolio.lifecycle_persistence import LifecycleProvenance
from btc_predictor.reporting.json_output import (
    ADVISORY_JSON_SCHEMA_VERSION,
    AdvisoryJsonResult,
    advisory_source_from_json,
    render_json_output,
)
from btc_predictor.reporting.recommendation import RecommendationRendererResult


DECISION_JOURNAL_FEATURE_ID = "RECOMMENDATION_DECISION_JOURNAL"
DECISION_JOURNAL_POLICY_VERSION = "RECOMMENDATION_DECISION_JOURNAL_V1"
DECISION_JOURNAL_TABLE = "recommendation_decisions"
DISCRETIONARY_REASON_POLICY_VERSION = "DISCRETIONARY_REASON_CODES_V1"

APPROVED = "APPROVED"
REJECTED = "REJECTED"
MODIFIED = "MODIFIED"
MISSED = "MISSED"

# An advisory that asks for no order cannot be modified or missed: there is no
# instruction to depart from and nothing that could fail to be executed.
ORDER_BEARING_ACTIONS = ("ENTER", "ADD", "TRIM", "EXIT")

# The advised values an operator can vary while still taking the advised
# action. The action itself is not modifiable: taking a different action is a
# rejection of the advised one, and recording it as a modification would make
# APPROVED, MODIFIED and REJECTED describe overlapping states.
MODIFIABLE_ADVISORY_FIELDS = (
    "entry_zone_lower",
    "entry_zone_upper",
    "initial_stop",
    "risk_fraction_nav",
    "suggested_notional",
)

DECISION_JOURNAL_REASON_CODES = (
    "DECISION_JOURNAL_RECORDED",
    "DECISION_JOURNAL_APPROVED",
    "DECISION_JOURNAL_REJECTED",
    "DECISION_JOURNAL_MODIFIED",
    "DECISION_JOURNAL_MISSED",
)

# BTC-201's declared order is also the persistence order. Callers may supply
# reasons in any order, but identical sets must produce identical records.
DISCRETIONARY_REASON_CODES = (
    "MACRO_CONCERN",
    "ENTRY_TOO_EXTENDED",
    "LOW_PERSONAL_CONFIDENCE",
    "ALREADY_EXPOSED",
    "UNAVAILABLE_TO_TRADE",
    "MODEL_DISAGREEMENT",
    "OTHER",
)

_CONFIG_METADATA_KEYS = ("config_version", "strategy_version", "parameter_set_id")
_RECORD_KEYS = (
    "feature_id",
    "policy_version",
    "provenance",
    "config_version",
    "evaluation_time",
    "decided_at",
    "decision",
    "advised_action",
    "modified_fields",
    "discretionary_reason_policy_version",
    "discretionary_reason_codes",
    "note",
    "advisory_schema_version",
    "advisory_body",
    "advisory_digest",
    "reason_codes",
)
# ``decision_id`` is generated by the database; every other column is written.
_WRITABLE_COLUMNS = frozenset(
    column.name for column in recommendation_decisions.columns
) - {"decision_id"}


@dataclass(frozen=True)
class RecommendationDecisionEntry:
    """One operator decision recorded against one rendered advisory."""

    feature_id: str
    policy_version: str
    provenance: LifecycleProvenance
    config_version: str
    evaluation_time: datetime
    decided_at: datetime
    decision: str
    advised_action: str
    modified_fields: tuple[str, ...]
    discretionary_reason_policy_version: str
    discretionary_reason_codes: tuple[str, ...]
    note: str | None
    advisory_body: str
    reason_codes: tuple[str, ...]

    @property
    def recommendation_id(self) -> int:
        return self.provenance.recommendation_id

    @property
    def advisory_schema_version(self) -> str:
        return ADVISORY_JSON_SCHEMA_VERSION

    @property
    def advisory_digest(self) -> str:
        """SHA-256 over the exact advisory bytes this decision answers."""

        return hashlib.sha256(self.advisory_body.encode("utf-8")).hexdigest()

    @property
    def config_metadata(self) -> dict[str, str]:
        return {
            "config_version": self.config_version,
            "strategy_version": self.provenance.strategy_version,
            "parameter_set_id": self.provenance.parameter_set_id,
        }

    def advisory(self) -> RecommendationRendererResult:
        """Replay the decided-against advisory from its stored document."""

        return _restore_advisory(self.advisory_body)

    def as_record(self) -> dict[str, Any]:
        """Return a self-validating record sufficient for exact replay."""

        verify_decision_entry(self)
        return {
            "feature_id": self.feature_id,
            "policy_version": self.policy_version,
            "provenance": self.provenance.as_record(),
            "config_version": self.config_version,
            "evaluation_time": self.evaluation_time.isoformat(),
            "decided_at": self.decided_at.isoformat(),
            "decision": self.decision,
            "advised_action": self.advised_action,
            "modified_fields": list(self.modified_fields),
            "discretionary_reason_policy_version": (
                self.discretionary_reason_policy_version
            ),
            "discretionary_reason_codes": list(self.discretionary_reason_codes),
            "note": self.note,
            "advisory_schema_version": self.advisory_schema_version,
            "advisory_body": self.advisory_body,
            "advisory_digest": self.advisory_digest,
            "reason_codes": list(self.reason_codes),
        }

    def as_row(self) -> dict[str, Any]:
        """Map onto the ``portfolio.recommendation_decisions`` columns."""

        self.as_record()
        row = {
            "recommendation_id": self.recommendation_id,
            "strategy_version": self.provenance.strategy_version,
            "parameter_set_id": self.provenance.parameter_set_id,
            "config_version": self.config_version,
            "evaluation_time": self.evaluation_time,
            "decided_at": self.decided_at,
            "decision": self.decision,
            "advised_action": self.advised_action,
            "modified_fields": list(self.modified_fields),
            "discretionary_reason_policy_version": (
                self.discretionary_reason_policy_version
            ),
            "discretionary_reason_codes": list(self.discretionary_reason_codes),
            "note": self.note,
            "advisory_schema_version": self.advisory_schema_version,
            "advisory_body": self.advisory_body,
            "advisory_digest": self.advisory_digest,
            "journal_policy_version": self.policy_version,
            "reason_codes": list(self.reason_codes),
        }
        if set(row) != _WRITABLE_COLUMNS:
            # A builder that drifted from the schema fails here rather than at
            # the first INSERT.
            raise ValueError(
                f"{DECISION_JOURNAL_TABLE} row does not match the table columns: "
                f"{sorted(set(row) ^ _WRITABLE_COLUMNS)}",
            )
        return row


def journal_recommendation_decision(
    advisory: RecommendationRendererResult | AdvisoryJsonResult,
    *,
    decision: str,
    decided_at: datetime,
    strategy_config: StrategyConfig,
    modified_fields: Sequence[str] = (),
    discretionary_reason_codes: Sequence[str] = (),
    note: str | None = None,
) -> RecommendationDecisionEntry:
    """Record one operator decision against one validated advisory."""

    if not isinstance(strategy_config, StrategyConfig):
        raise TypeError("strategy_config must be a StrategyConfig")
    recorded = _decision(decision)
    body = _advisory_body(advisory)
    source = _restore_advisory(body)
    metadata = _config_metadata(strategy_config.run_metadata())
    if _config_metadata(source.config_metadata) != metadata:
        raise ValueError("advisory config identity does not match strategy_config")

    view = source.recommendation
    entry = RecommendationDecisionEntry(
        feature_id=DECISION_JOURNAL_FEATURE_ID,
        policy_version=DECISION_JOURNAL_POLICY_VERSION,
        provenance=LifecycleProvenance.from_config(
            strategy_config,
            recommendation_id=view.recommendation_id,
        ),
        config_version=metadata["config_version"],
        evaluation_time=view.evaluation_time,
        decided_at=_utc_datetime(decided_at, "decided_at"),
        decision=recorded,
        advised_action=view.action,
        modified_fields=_modified_fields(
            modified_fields,
            decision=recorded,
            advisory=source,
        ),
        discretionary_reason_policy_version=DISCRETIONARY_REASON_POLICY_VERSION,
        discretionary_reason_codes=_discretionary_reason_codes(
            discretionary_reason_codes,
        ),
        note=_optional_note(note),
        advisory_body=body,
        reason_codes=_reason_codes(recorded),
    )
    entry.as_record()
    return entry


def recommendation_decision_from_record(
    source: Mapping[str, Any] | Any,
) -> RecommendationDecisionEntry:
    """Restore a persisted decision entry and reject replay drift."""

    row = _as_mapping(source, "decision journal record")
    unknown = set(row) - set(_RECORD_KEYS)
    if unknown:
        raise ValueError(
            f"decision journal record has unknown fields: {sorted(unknown)}",
        )
    entry = RecommendationDecisionEntry(
        feature_id=row.get("feature_id"),
        policy_version=row.get("policy_version"),
        provenance=_provenance(row.get("provenance")),
        config_version=_identity(row.get("config_version"), "config_version"),
        evaluation_time=_utc_datetime(row.get("evaluation_time"), "evaluation_time"),
        decided_at=_utc_datetime(row.get("decided_at"), "decided_at"),
        decision=row.get("decision"),
        advised_action=row.get("advised_action"),
        modified_fields=_string_sequence(
            row.get("modified_fields"),
            "modified_fields",
        ),
        discretionary_reason_policy_version=row.get(
            "discretionary_reason_policy_version",
        ),
        discretionary_reason_codes=_string_sequence(
            row.get("discretionary_reason_codes"),
            "discretionary_reason_codes",
        ),
        note=row.get("note"),
        advisory_body=_body(row.get("advisory_body")),
        reason_codes=_string_sequence(row.get("reason_codes"), "reason_codes"),
    )
    if entry.as_record() != dict(row):
        raise ValueError("decision journal record does not match its validated entry")
    return entry


def verify_decision_entry(entry: RecommendationDecisionEntry) -> None:
    """Raise unless the decision is consistent with the advisory it answers."""

    if not isinstance(entry, RecommendationDecisionEntry):
        raise TypeError("entry must be a RecommendationDecisionEntry")
    if entry.feature_id != DECISION_JOURNAL_FEATURE_ID:
        raise ValueError(f"feature_id must be {DECISION_JOURNAL_FEATURE_ID}")
    if entry.policy_version != DECISION_JOURNAL_POLICY_VERSION:
        raise ValueError(f"policy_version must be {DECISION_JOURNAL_POLICY_VERSION}")

    decision = _decision(entry.decision)
    # Restoring from the stored bytes is what proves the document is intact and
    # canonically encoded; the entry is never trusted to describe itself.
    advisory = _restore_advisory(entry.advisory_body)
    view = advisory.recommendation
    columns = entry.provenance.as_columns()
    if columns["recommendation_id"] != view.recommendation_id:
        raise ValueError("decision is not attributed to the advised recommendation")
    if _config_metadata(advisory.config_metadata) != _config_metadata(
        entry.config_metadata,
    ):
        raise ValueError("decision config identity does not match the advisory")
    if _utc_datetime(entry.evaluation_time, "evaluation_time") != view.evaluation_time:
        raise ValueError("evaluation_time does not match the advised recommendation")
    if _utc_datetime(entry.decided_at, "decided_at") < view.evaluation_time:
        raise ValueError("decided_at must not precede the advisory it answers")
    if entry.advised_action != view.action:
        raise ValueError("advised_action does not match the advised recommendation")
    if decision in (MODIFIED, MISSED):
        _require_order_bearing(decision, advisory)
    if entry.modified_fields != _modified_fields(
        entry.modified_fields,
        decision=decision,
        advisory=advisory,
    ):
        raise ValueError("modified_fields are not in canonical advisory order")
    if (
        entry.discretionary_reason_policy_version
        != DISCRETIONARY_REASON_POLICY_VERSION
    ):
        raise ValueError(
            "discretionary_reason_policy_version must be "
            f"{DISCRETIONARY_REASON_POLICY_VERSION}",
        )
    if entry.discretionary_reason_codes != _discretionary_reason_codes(
        entry.discretionary_reason_codes,
    ):
        raise ValueError("discretionary reason codes are not in canonical order")
    _optional_note(entry.note)
    if entry.reason_codes != _reason_codes(decision):
        raise ValueError("reason_codes do not match the recorded decision")


def _advisory_body(
    advisory: RecommendationRendererResult | AdvisoryJsonResult,
) -> str:
    if isinstance(advisory, RecommendationRendererResult):
        return render_json_output(advisory).body
    if isinstance(advisory, AdvisoryJsonResult):
        advisory.as_record()
        if advisory.document_type != "recommendation":
            raise ValueError(
                "a decision can only be recorded against a recommendation advisory",
            )
        return advisory.body
    raise TypeError(
        "advisory must be a RecommendationRendererResult or an "
        "AdvisoryJsonResult recommendation document",
    )


def _restore_advisory(body: Any) -> RecommendationRendererResult:
    source = advisory_source_from_json(_body(body))
    if not isinstance(source, RecommendationRendererResult):
        raise ValueError(
            "a decision can only be recorded against a recommendation advisory",
        )
    return source


def _modified_fields(
    value: Any,
    *,
    decision: str,
    advisory: RecommendationRendererResult,
) -> tuple[str, ...]:
    fields = _string_sequence(value, "modified_fields")
    unknown = set(fields) - set(MODIFIABLE_ADVISORY_FIELDS)
    if unknown:
        raise ValueError(
            f"modified_fields must be drawn from {MODIFIABLE_ADVISORY_FIELDS}",
        )
    if len(set(fields)) != len(fields):
        raise ValueError("modified_fields must not repeat a field")
    if decision != MODIFIED:
        if fields:
            raise ValueError(f"{decision} cannot name modified advisory fields")
        return ()
    if not fields:
        raise ValueError("MODIFIED must name the advised fields departed from")
    _require_order_bearing(decision, advisory)
    absent = tuple(
        name for name in fields if getattr(advisory.recommendation, name) is None
    )
    if absent:
        raise ValueError(
            f"the advisory did not state these modified fields: {sorted(absent)}",
        )
    # Canonical order keeps two operators recording the same modification as
    # the same row regardless of the order they listed the fields in.
    return tuple(name for name in MODIFIABLE_ADVISORY_FIELDS if name in set(fields))


def _require_order_bearing(
    decision: str,
    advisory: RecommendationRendererResult,
) -> None:
    if advisory.recommendation.action not in ORDER_BEARING_ACTIONS:
        raise ValueError(
            f"{decision} requires an advisory action in {ORDER_BEARING_ACTIONS}",
        )


def _decision(value: Any) -> str:
    if not isinstance(value, str):
        raise TypeError("decision must be a string")
    if value not in RECOMMENDATION_DECISIONS:
        raise ValueError(f"decision must be one of {RECOMMENDATION_DECISIONS}")
    return value


def _reason_codes(decision: str) -> tuple[str, ...]:
    return ("DECISION_JOURNAL_RECORDED", f"DECISION_JOURNAL_{decision}")


def _discretionary_reason_codes(value: Any) -> tuple[str, ...]:
    codes = _string_sequence(value, "discretionary_reason_codes")
    unknown = set(codes) - set(DISCRETIONARY_REASON_CODES)
    if unknown:
        raise ValueError(
            "discretionary_reason_codes must be drawn from "
            f"{DISCRETIONARY_REASON_CODES}",
        )
    if len(set(codes)) != len(codes):
        raise ValueError("discretionary_reason_codes must not repeat a code")
    selected = set(codes)
    return tuple(code for code in DISCRETIONARY_REASON_CODES if code in selected)


def _provenance(source: Mapping[str, Any] | Any) -> LifecycleProvenance:
    if isinstance(source, LifecycleProvenance):
        return source
    row = _as_mapping(source, "provenance")
    if set(row) != {"recommendation_id", "strategy_version", "parameter_set_id"}:
        raise ValueError(
            "provenance must contain recommendation_id, strategy_version and "
            "parameter_set_id",
        )
    return LifecycleProvenance(
        recommendation_id=row["recommendation_id"],
        strategy_version=row["strategy_version"],
        parameter_set_id=row["parameter_set_id"],
    )


def _config_metadata(source: Mapping[str, Any] | Any) -> dict[str, str]:
    row = _as_mapping(source, "config_metadata")
    if set(row) != set(_CONFIG_METADATA_KEYS):
        raise ValueError(f"config_metadata must exactly contain {_CONFIG_METADATA_KEYS}")
    return {
        key: _identity(row[key], f"config_metadata.{key}")
        for key in _CONFIG_METADATA_KEYS
    }


def _as_mapping(source: Mapping[str, Any] | Any, name: str) -> Mapping[str, Any]:
    if isinstance(source, Mapping):
        return source
    row = getattr(source, "_mapping", None)
    if isinstance(row, Mapping):
        return row
    raise TypeError(f"{name} must be a mapping or database row")


def _utc_datetime(value: Any, name: str) -> datetime:
    parsed = value
    if isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ValueError(f"{name} must be an ISO-8601 datetime") from exc
    if not isinstance(parsed, datetime):
        raise TypeError(f"{name} must be a datetime or ISO-8601 string")
    return require_utc_datetime(parsed, name)


def _string_sequence(value: Any, name: str) -> tuple[str, ...]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise TypeError(f"{name} must be a sequence of strings")
    values = tuple(value)
    if any(not isinstance(item, str) or not item.strip() for item in values):
        raise ValueError(f"{name} must contain non-empty strings")
    return values


def _identity(value: Any, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a non-empty string")
    return value


def _optional_note(value: Any) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise TypeError("note must be a string")
    if not value or value != value.strip() or "\n" in value or "\r" in value:
        raise ValueError("note must be non-empty single-line text")
    return value


def _body(value: Any) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError("advisory_body must be non-empty canonical advisory JSON")
    return value


__all__ = [
    "APPROVED",
    "DECISION_JOURNAL_FEATURE_ID",
    "DECISION_JOURNAL_POLICY_VERSION",
    "DECISION_JOURNAL_REASON_CODES",
    "DECISION_JOURNAL_TABLE",
    "DISCRETIONARY_REASON_CODES",
    "DISCRETIONARY_REASON_POLICY_VERSION",
    "MISSED",
    "MODIFIABLE_ADVISORY_FIELDS",
    "MODIFIED",
    "ORDER_BEARING_ACTIONS",
    "RECOMMENDATION_DECISIONS",
    "REJECTED",
    "RecommendationDecisionEntry",
    "journal_recommendation_decision",
    "recommendation_decision_from_record",
    "verify_decision_entry",
]
