"""Reporting and advisory-output modules."""

from btc_predictor.reporting.recommendation import (
    RECOMMENDATION_RENDERER_FEATURE_ID,
    RECOMMENDATION_RENDERER_MEDIA_TYPE,
    RECOMMENDATION_RENDERER_REASON_CODES,
    RECOMMENDATION_RENDERER_VERSION,
    AddConditionPolicy,
    PredictorRunView,
    RankedRecommendationReason,
    RecommendationRendererResult,
    RecommendationView,
    recommendation_renderer_from_record,
    render_recommendation,
)
from btc_predictor.reporting.position_management import (
    POSITION_MANAGEMENT_ACTIONS,
    POSITION_MANAGEMENT_REPORT_FEATURE_ID,
    POSITION_MANAGEMENT_REPORT_MEDIA_TYPE,
    POSITION_MANAGEMENT_REPORT_REASON_CODES,
    POSITION_MANAGEMENT_REPORT_VERSION,
    PositionManagementMetrics,
    PositionManagementReportResult,
    PositionMark,
    position_management_report_from_record,
    render_position_management_report,
)
from btc_predictor.reporting.json_output import (
    ADVISORY_JSON_DOCUMENT_TYPES,
    ADVISORY_JSON_ENCODING,
    ADVISORY_JSON_FEATURE_ID,
    ADVISORY_JSON_MEDIA_TYPE,
    ADVISORY_JSON_REASON_CODES,
    ADVISORY_JSON_SCHEMA_VERSION,
    AdvisoryJsonResult,
    advisory_json_from_record,
    advisory_source_from_json,
    render_json_output,
)

__all__ = [
    "RECOMMENDATION_RENDERER_FEATURE_ID",
    "RECOMMENDATION_RENDERER_MEDIA_TYPE",
    "RECOMMENDATION_RENDERER_REASON_CODES",
    "RECOMMENDATION_RENDERER_VERSION",
    "AddConditionPolicy",
    "PredictorRunView",
    "RankedRecommendationReason",
    "RecommendationRendererResult",
    "RecommendationView",
    "recommendation_renderer_from_record",
    "render_recommendation",
    "POSITION_MANAGEMENT_ACTIONS",
    "POSITION_MANAGEMENT_REPORT_FEATURE_ID",
    "POSITION_MANAGEMENT_REPORT_MEDIA_TYPE",
    "POSITION_MANAGEMENT_REPORT_REASON_CODES",
    "POSITION_MANAGEMENT_REPORT_VERSION",
    "PositionManagementMetrics",
    "PositionManagementReportResult",
    "PositionMark",
    "position_management_report_from_record",
    "render_position_management_report",
    "ADVISORY_JSON_DOCUMENT_TYPES",
    "ADVISORY_JSON_ENCODING",
    "ADVISORY_JSON_FEATURE_ID",
    "ADVISORY_JSON_MEDIA_TYPE",
    "ADVISORY_JSON_REASON_CODES",
    "ADVISORY_JSON_SCHEMA_VERSION",
    "AdvisoryJsonResult",
    "advisory_json_from_record",
    "advisory_source_from_json",
    "render_json_output",
]
