"""Reporting and advisory-output modules."""

from btc_predictor.reporting.recommendation import (
    RECOMMENDATION_RENDERER_FEATURE_ID,
    RECOMMENDATION_RENDERER_MEDIA_TYPE,
    RECOMMENDATION_RENDERER_REASON_CODES,
    RECOMMENDATION_RENDERER_VERSION,
    AddConditionPolicy,
    PredictorRunView,
    RankedRecommendationReason,
    RecommendationRendererResult,
    RecommendationView,
    recommendation_renderer_from_record,
    render_recommendation,
)
from btc_predictor.reporting.position_management import (
    POSITION_MANAGEMENT_ACTIONS,
    POSITION_MANAGEMENT_REPORT_FEATURE_ID,
    POSITION_MANAGEMENT_REPORT_MEDIA_TYPE,
    POSITION_MANAGEMENT_REPORT_REASON_CODES,
    POSITION_MANAGEMENT_REPORT_VERSION,
    PositionManagementMetrics,
    PositionManagementReportResult,
    PositionMark,
    position_management_report_from_record,
    render_position_management_report,
)

__all__ = [
    "RECOMMENDATION_RENDERER_FEATURE_ID",
    "RECOMMENDATION_RENDERER_MEDIA_TYPE",
    "RECOMMENDATION_RENDERER_REASON_CODES",
    "RECOMMENDATION_RENDERER_VERSION",
    "AddConditionPolicy",
    "PredictorRunView",
    "RankedRecommendationReason",
    "RecommendationRendererResult",
    "RecommendationView",
    "recommendation_renderer_from_record",
    "render_recommendation",
    "POSITION_MANAGEMENT_ACTIONS",
    "POSITION_MANAGEMENT_REPORT_FEATURE_ID",
    "POSITION_MANAGEMENT_REPORT_MEDIA_TYPE",
    "POSITION_MANAGEMENT_REPORT_REASON_CODES",
    "POSITION_MANAGEMENT_REPORT_VERSION",
    "PositionManagementMetrics",
    "PositionManagementReportResult",
    "PositionMark",
    "position_management_report_from_record",
    "render_position_management_report",
]
