"""Reporting and advisory-output modules."""

from btc_predictor.reporting.recommendation import (
    RECOMMENDATION_RENDERER_FEATURE_ID,
    RECOMMENDATION_RENDERER_MEDIA_TYPE,
    RECOMMENDATION_RENDERER_REASON_CODES,
    RECOMMENDATION_RENDERER_VERSION,
    AddConditionPolicy,
    PredictorRunView,
    RankedRecommendationReason,
    RecommendationRendererResult,
    RecommendationView,
    recommendation_renderer_from_record,
    render_recommendation,
)
from btc_predictor.reporting.position_management import (
    POSITION_MANAGEMENT_ACTIONS,
    POSITION_MANAGEMENT_REPORT_FEATURE_ID,
    POSITION_MANAGEMENT_REPORT_MEDIA_TYPE,
    POSITION_MANAGEMENT_REPORT_REASON_CODES,
    POSITION_MANAGEMENT_REPORT_VERSION,
    PositionManagementMetrics,
    PositionManagementReportResult,
    PositionMark,
    position_management_report_from_record,
    render_position_management_report,
)
from btc_predictor.reporting.json_output import (
    ADVISORY_JSON_DOCUMENT_TYPES,
    ADVISORY_JSON_ENCODING,
    ADVISORY_JSON_FEATURE_ID,
    ADVISORY_JSON_MEDIA_TYPE,
    ADVISORY_JSON_REASON_CODES,
    ADVISORY_JSON_SCHEMA_VERSION,
    AdvisoryJsonResult,
    advisory_json_from_record,
    advisory_source_from_json,
    render_json_output,
)
from btc_predictor.reporting.daily_status import (
    DAILY_SYSTEM_STATUS_FEATURE_ID,
    DAILY_SYSTEM_STATUS_MEDIA_TYPE,
    DAILY_SYSTEM_STATUS_REASON_CODES,
    DAILY_SYSTEM_STATUS_VERSION,
    DATA_QUALITY_FAIL,
    DATA_QUALITY_PASS,
    DATA_QUALITY_STATUSES,
    PAPER_PORTFOLIO_ACTIVE_FLAT,
    PAPER_PORTFOLIO_ACTIVE_MONITORING,
    PAPER_PORTFOLIO_ACTIVE_OPEN,
    PAPER_PORTFOLIO_ARCHIVED,
    PAPER_PORTFOLIO_STATUSES,
    DailySystemStatusResult,
    DataQualityComponentStatus,
    DataQualityStatus,
    PaperPortfolioStatus,
    daily_system_status_from_record,
    render_daily_system_status,
)
from btc_predictor.reporting.weekly_strategy import (
    WEEKLY_STRATEGY_REPORT_FEATURE_ID,
    WEEKLY_STRATEGY_REPORT_LOOKBACK,
    WEEKLY_STRATEGY_REPORT_MEDIA_TYPE,
    WEEKLY_STRATEGY_REPORT_REASON_CODES,
    WEEKLY_STRATEGY_REPORT_VERSION,
    ScoreMovement,
    StrategyStateChange,
    WeeklyStrategyReportResult,
    render_weekly_strategy_report,
    weekly_strategy_report_from_record,
)

__all__ = [
    "RECOMMENDATION_RENDERER_FEATURE_ID",
    "RECOMMENDATION_RENDERER_MEDIA_TYPE",
    "RECOMMENDATION_RENDERER_REASON_CODES",
    "RECOMMENDATION_RENDERER_VERSION",
    "AddConditionPolicy",
    "PredictorRunView",
    "RankedRecommendationReason",
    "RecommendationRendererResult",
    "RecommendationView",
    "recommendation_renderer_from_record",
    "render_recommendation",
    "POSITION_MANAGEMENT_ACTIONS",
    "POSITION_MANAGEMENT_REPORT_FEATURE_ID",
    "POSITION_MANAGEMENT_REPORT_MEDIA_TYPE",
    "POSITION_MANAGEMENT_REPORT_REASON_CODES",
    "POSITION_MANAGEMENT_REPORT_VERSION",
    "PositionManagementMetrics",
    "PositionManagementReportResult",
    "PositionMark",
    "position_management_report_from_record",
    "render_position_management_report",
    "ADVISORY_JSON_DOCUMENT_TYPES",
    "ADVISORY_JSON_ENCODING",
    "ADVISORY_JSON_FEATURE_ID",
    "ADVISORY_JSON_MEDIA_TYPE",
    "ADVISORY_JSON_REASON_CODES",
    "ADVISORY_JSON_SCHEMA_VERSION",
    "AdvisoryJsonResult",
    "advisory_json_from_record",
    "advisory_source_from_json",
    "render_json_output",
    "DAILY_SYSTEM_STATUS_FEATURE_ID",
    "DAILY_SYSTEM_STATUS_MEDIA_TYPE",
    "DAILY_SYSTEM_STATUS_REASON_CODES",
    "DAILY_SYSTEM_STATUS_VERSION",
    "DATA_QUALITY_FAIL",
    "DATA_QUALITY_PASS",
    "DATA_QUALITY_STATUSES",
    "PAPER_PORTFOLIO_ACTIVE_FLAT",
    "PAPER_PORTFOLIO_ACTIVE_MONITORING",
    "PAPER_PORTFOLIO_ACTIVE_OPEN",
    "PAPER_PORTFOLIO_ARCHIVED",
    "PAPER_PORTFOLIO_STATUSES",
    "DailySystemStatusResult",
    "DataQualityComponentStatus",
    "DataQualityStatus",
    "PaperPortfolioStatus",
    "daily_system_status_from_record",
    "render_daily_system_status",
    "WEEKLY_STRATEGY_REPORT_FEATURE_ID",
    "WEEKLY_STRATEGY_REPORT_LOOKBACK",
    "WEEKLY_STRATEGY_REPORT_MEDIA_TYPE",
    "WEEKLY_STRATEGY_REPORT_REASON_CODES",
    "WEEKLY_STRATEGY_REPORT_VERSION",
    "ScoreMovement",
    "StrategyStateChange",
    "WeeklyStrategyReportResult",
    "render_weekly_strategy_report",
    "weekly_strategy_report_from_record",
    "DRAWDOWN_AVAILABLE",
    "DRAWDOWN_MISSING_RETURNS",
    "DRAWDOWN_NO_CLOSED_TRADES",
    "DRAWDOWN_NON_POSITIVE_EQUITY",
    "HUMAN_ACTUAL",
    "MODEL_HUMAN_ACTUAL_RETURN_POLICY_VERSION",
    "MODEL_HUMAN_ARMS",
    "MODEL_HUMAN_COMPARISON_FEATURE_ID",
    "MODEL_HUMAN_COMPARISON_POLICY_VERSION",
    "MODEL_HUMAN_COMPARISON_REASON_CODES",
    "MODEL_HUMAN_DRAWDOWN_POLICY_VERSION",
    "MODEL_HUMAN_PAPER_RETURN_POLICY_VERSION",
    "MODEL_HUMAN_SHARPE_POLICY_VERSION",
    "MODEL_PAPER",
    "MODEL_PLUS_HUMAN",
    "PROFIT_FACTOR_ALL_FLAT",
    "PROFIT_FACTOR_AVAILABLE",
    "PROFIT_FACTOR_NO_LOSSES",
    "PROFIT_FACTOR_NO_MEASURED_TRADES",
    "RETURN_AVAILABLE",
    "RETURN_NOT_MEASURED",
    "RETURN_OPEN",
    "R_AVAILABLE",
    "R_MISSING_INITIAL_STOP",
    "R_NON_ADVERSE_INITIAL_STOP",
    "R_NOT_MEASURED",
    "R_OPEN",
    "SHARPE_AVAILABLE",
    "SHARPE_INSUFFICIENT_TRADES",
    "SHARPE_MISSING_RETURNS",
    "SHARPE_ZERO_DISPERSION",
    "ModelHumanArm",
    "ModelHumanComparisonError",
    "ModelHumanComparisonReport",
    "ModelHumanMetrics",
    "ModelHumanTradeOutcome",
    "build_model_human_comparison",
    "restore_model_human_comparison",
]


_MODEL_HUMAN_EXPORTS = frozenset(
    __all__[__all__.index("DRAWDOWN_AVAILABLE") :]
)


def __getattr__(name: str):
    """Load BTC-203 exports without cycling through the decision journal."""

    if name not in _MODEL_HUMAN_EXPORTS:
        raise AttributeError(name)
    from btc_predictor.reporting import model_human_comparison

    return getattr(model_human_comparison, name)
