"""Typed NumPy/SciPy quantitative-core conventions."""

from btc_predictor.quant.arrays import (
    DEFAULT_TOLERANCE,
    FLOAT_DTYPE,
    NAN_POLICIES,
    QUANT_POLICY_VERSION,
    FloatArray,
    NanPolicy,
    NumericInputError,
    NumericTolerance,
    as_float64_array,
    as_float64_matrix,
    as_float64_vector,
    is_effectively_zero,
    require_probability,
    require_same_shape,
)
from btc_predictor.quant.simulation import normal_samples
from btc_predictor.quant.rolling import (
    PARITY_ABSOLUTE_TOLERANCE,
    PARITY_RELATIVE_TOLERANCE,
    ROLLING_NAN_POLICIES,
    RollingNanPolicy,
    average_true_range,
    historical_normalize,
    realized_volatility,
    rolling_mean,
    rolling_percentile,
    rolling_volatility,
    rolling_zscore,
    simple_returns,
    true_range,
)


__all__ = [
    "DEFAULT_TOLERANCE",
    "FLOAT_DTYPE",
    "NAN_POLICIES",
    "PARITY_ABSOLUTE_TOLERANCE",
    "PARITY_RELATIVE_TOLERANCE",
    "QUANT_POLICY_VERSION",
    "ROLLING_NAN_POLICIES",
    "FloatArray",
    "NanPolicy",
    "NumericInputError",
    "NumericTolerance",
    "RollingNanPolicy",
    "average_true_range",
    "as_float64_array",
    "as_float64_matrix",
    "as_float64_vector",
    "is_effectively_zero",
    "historical_normalize",
    "normal_samples",
    "realized_volatility",
    "require_probability",
    "require_same_shape",
    "rolling_mean",
    "rolling_percentile",
    "rolling_volatility",
    "rolling_zscore",
    "simple_returns",
    "true_range",
]
